### ISSUE TITLE
Issue with the precision of quality flag

### ISSUE THREAD

**Issue by diesseh** [maawoo/gedixr#18]
Hi Marco,

Thanks again for this script

I am getting this error

gdf_l2a = extract_data(directory=gedi_dir, gedi_product='L2A', only_full_power=True, subset_vector=vec_path)
Traceback (most recent call last):
File "", line 1, in
TypeError: extract_data() got an unexpected keyword argument 'only_full_power'

**Comment by maawoo** [comment]
Hi @diesseh, 
there have been some changes to the `extract_data`-function that are not reflected in the Readme yet (#16) . I will update it as soon as possible! 

The `only_full_power`-parameter has been replaced by `beams`, which accepts a list of beam names (e.g., `['BEAM0101', 'BEAM0110', 'BEAM1000', 'BEAM1011']`). If you only want to extract data from the full power beams, you can do the following: 

```python
from gedixr.gedi import extract_data, FULL_POWER_BEAMS

gdf_l2a = extract_data(directory=gedi_dir, gedi_product='L2A', beams=FULL_POWER_BEAMS, subset_vector=vec_path)
```

Let me know if that works for you.
